### ISSUE TITLE
请教有关jlu校园网的问题

### ISSUE THREAD

**Issue by namina123** [drcoms/jlu-drcom-client#21]
请问一下，我使用的是吉林大学ver5.2.1(D)版客户端，pc和pandorabox上都正确安装了python2.7，使用的是newclient.py这个文件，电脑上测试成功，但是到路由器上却出现了图片上这样的情况，请问该怎么解决呢
![1598770723496](https://user-images.githubusercontent.com/70464692/91653238-6b892280-ea64-11ea-9b5b-8fde10035375.jpg)

**Comment by windmzx** [comment]
是否应该先检查一下mac克隆，ping一下网关和认证服务器

**Comment by namina123** [comment]
> 是否应该先检查一下mac克隆，ping一下网关和认证服务器

您好，在python脚本百试不通后，我重新刷了openwrt并安装了python3。我已经确定我的路由器正确安装了python3，改换为python3脚本后，运行时出现了如下错误
root@HiWiFi:~# python3 /usr/bin/drcom
\Traceback (most recent call last):
File "/usr/bin/drcom", line 394, in 
main()
File "/usr/bin/drcom", line 373, in main
execfile(CONF, globals())
NameError: name 'execfile' is not defined
本人没有学过python，所以参照网上的方法，将第373行的execfile(CONF, globals())改为了exec(open(CONF).read())
此时却又出现了如下错误
[salt] b'gg\x10\x00'
Traceback (most recent call last):
File "/usr/bin/drcom", line 394, in 
main()
File "/usr/bin/drcom", line 380, in main
package_tail = login(username, password, server)
File "/usr/bin/drcom", line 307, in login
packet = mkpkt(salt, usr, pwd, mac) #生成数据包
File "/usr/bin/drcom", line 256, in mkpkt
data += md5sum(b'\x03\x01'+salt+pwd)
TypeError: can't concat str to bytes
请问该如何解决呢

**Comment by windmzx** [comment]
没有复现，可以尝试下加 .deode()

**Comment by leviolet** [comment]
Python2和3处理bytes和str的方式有些不同，需要先解码才能互相连接
可以试一下刚出炉不久的  #19 ?
（逃）

**Comment by leviolet** [comment]
由于手头没有Linux设备，这个...我提交的Python3版本只在Windows下测试过。而且只是机械的翻译，关于execfile这块说实话我没看懂...

**Comment by namina123** [comment]
> 由于手头没有Linux设备，这个...我提交的Python3版本只在Windows下测试过。而且只是机械的翻译，关于execfile这块说实话我没看懂...
> 而且看源代码貌似是有守护进程之类的东西，就一直没敢动。
> 所以最好还是使用久经考验的Python2版本吧
尝试良久，我最后把256行的代码改成了 data += md5sum(bytes.decode(b'\x03\x01')+salt.decode('utf-8','ignore')+pwd) 后不再报告此错误，但是257行却又出现了另一类似错误，请问该如何修改呢

**Comment by namina123** [comment]
> 由于手头没有Linux设备，这个...我提交的Python3版本只在Windows下测试过。而且只是机械的翻译，关于execfile这块说实话我没看懂...
> 而且看源代码貌似是有守护进程之类的东西，就一直没敢动。
> 所以最好还是使用久经考验的Python2版本吧

尝试良久，我最后把256行的代码改成了 data += md5sum(bytes.decode(b'\x03\x01')+salt.decode('utf-8','ignore')+pwd) 后不再报告此错误，但是257行却又出现了另一类似错误，请问该如何修改呢

**Comment by leviolet** [comment]
> > 由于手头没有Linux设备，这个...我提交的Python3版本只在Windows下测试过。而且只是机械的翻译，关于execfile这块说实话我没看懂...
> > 而且看源代码貌似是有守护进程之类的东西，就一直没敢动。
> > 所以最好还是使用久经考验的Python2版本吧
> 
> 尝试良久，我最后把256行的代码改成了 data += md5sum(bytes.decode(b'\x03\x01')+salt.decode('utf-8','ignore')+pwd) 后不再报告此错误，但是257行却又出现了另一类似错误，请问该如何修改呢

这个...我觉得这个字符串编码问题不会因为操作系统而不同，更像是调用exec的时候没有像原来那样传入globals()参数

**Comment by namina123** [comment]
> 由于手头没有Linux设备，这个...我提交的Python3版本只在Windows下测试过。而且只是机械的翻译，关于execfile这块说实话我没看懂...
> 而且看源代码貌似是有守护进程之类的东西，就一直没敢动。
> 所以最好还是使用久经考验的Python2版本吧

我目前使用的openwrt系统版本安装python2会出现hashlib无法关联的请况，而能正常安装python2的pandarobox却无法正常开关机，所以不得不尝试python3版本

**Comment by leviolet** [comment]
> > 由于手头没有Linux设备，这个...我提交的Python3版本只在Windows下测试过。而且只是机械的翻译，关于execfile这块说实话我没看懂...
> > 而且看源代码貌似是有守护进程之类的东西，就一直没敢动。
> > 所以最好还是使用久经考验的Python2版本吧
> 
> 我目前使用的openwrt系统版本安装python2会出现hashlib无法关联的请况，而能正常安装python2的pandarobox却无法正常开关机，所以不得不尝试python3版本

可以尝试一下其他语言的版本，比如Java版和C语言版，项目里还有一个for openwrt的文件夹。这个bug我没法修，要修也只是删掉守护进程这块，等大佬们来吧

**Comment by mchome** [comment]
試試 https://github.com/mchome/openwrt-dogcom

**Comment by namina123** [comment]
> > > 由于手头没有Linux设备，这个...我提交的Python3版本只在Windows下测试过。而且只是机械的翻译，关于execfile这块说实话我没看懂...
> > > 而且看源代码貌似是有守护进程之类的东西，就一直没敢动。
> > > 所以最好还是使用久经考验的Python2版本吧
> > 
> > 
> > 我目前使用的openwrt系统版本安装python2会出现hashlib无法关联的请况，而能正常安装python2的pandarobox却无法正常开关机，所以不得不尝试python3版本
> 
> 可以尝试一下其他语言的版本，比如Java版和C语言版，项目里还有一个for openwrt的文件夹。这个bug我没法修，要修也只是删掉守护进程这块，等大佬们来吧

好的，谢谢大佬

**Comment by windmzx** [comment]
还是用c比较好。。。路由器上的最优解

**Comment by Yurzi** [comment]
刚来吉林大学的软件工程的新生，好不容易找到这里，能冒昧的问些关于吉林大学校园网的问题吗？
1.现在的github上的代码适用于现在版本的Drcom客户端吗？
2.如何通过刷路由器来实现自己搭建wifi呢？（纯萌新，略有Linux等相关的操作知识）希望可以推荐些教程
3.如果刷路由器的话什么样的路由器和固件比较推荐呢？
4.后续如果Drcom版本更新，以后如何继续搞事情qwq。
5.想了解一些如何破解吉林大学drcom的方法，想学习方法。

**Comment by leviolet** [comment]
@Yurzi 

1. 大部分适用,Drcom好多年没更新了
2. 具体细节不太清楚,不过校园网规定中严禁使用路由器等设备来实现多设备共用IP
3. 不清楚(我就是个有时候脸皮比较厚的萌新)
4. 后续如果Drcom更新,得先等学网安 ~~(也有可能是计算机,软件,甚至是地质的)~~ 的同学分析出协议来
5. 如果说是想实现一个客户端,可以参考 YouthLin 学长的 [jlu-drcom-protocol](https://github.com/drcoms/jlu-drcom-client/blob/master/jlu-drcom-java/jlu-drcom-protocol.md) 协议分析, 写的很清楚

**Comment by Yurzi** [comment]
@leviolet 
多谢学长指点迷津，折腾这个并不是为了白嫖上网，只是觉得学校的无线网络实在是太慢了，想自己搞个路由器什么的提升下网速（好下载游戏doge）

**Comment by Yurzi** [comment]
@leviolet 
学长，对不起，我还有一个问题想请教：
  为什么有线的校园网有时候会能上qq却不能打开网页（大概dns解析有问题）这是校园网的DNS服务器抽搐了吗？（用的校园网指定的DNS）
  如果是能不能自己切换DNS服务器，如果可以切换，有什么好的DNS服务器推荐吗？
  谢谢学长了qwq。

**Comment by leviolet** [comment]
> 为什么有线的校园网有时候会能上qq却不能打开网页（大概dns解析有问题）这是校园网的DNS服务器抽搐了吗？（用的校园网指定的DNS）
> 如果是能不能自己切换DNS服务器，如果可以切换，有什么好的DNS服务器推荐吗？

DNS经常抽,网易云有时候都缓冲不出来
无线的应该是可以换DNS的,有线的我没试过,一直都是用的无线的
